fun main() {
    print("Nama: ") 
    println("Arie Ginanjar Januar")
    print("Jenis Kelamin: ") 
    println("Laki-laki")
    print("Ttl: ") 
    println("Bandung, 07 Januari 2007")
    print("Sekolah: ") 
    println("SMKN 07 Baleendah")
    print("Alamat: ") 
    println("Kp.Cileutik")
    print("Hobby: ")  
    println("Main game")
    print("Cita-cita: ") 
    println("Programer")
}